# Setup
title:               A Survey of Non-functional Optimizationfor Mobile Applications
tagline:             'a living literature review'
description:         'Research on non-functional characteristics of mobile applications.'
url:                 http://solar.cs.ucl.ac.uk/appoptimization.github.io/
baseurl:             ''
