# Setup
title:               A Survey of Non-functional Optimization for Mobile Applications
tagline:             'a living literature review'
description:         'Research on non-functional characteristics of mobile applications'
url:                 https://solar.cs.ucl.ac.uk/appoptimization.github.io/
baseurl:             

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
